### ISSUE TITLE
Spacing issue + About button not working + Edit window off-center

### ISSUE THREAD

**Issue by Zabriskije** [bentettmar/barnotes#7]
- There is a text spacing issue in the info window (or at least is different from the preview on the website):
<img width="462" alt="Schermata 2022-04-08 alle 16 17 07" src="https://user-images.githubusercontent.com/101254295/162455080-b7084afd-aa22-4548-9d96-bd998d449607.png">

- The `About` button in the menu bar doesn't work.

- When you input a longer text than the one already displayed, the edit window is slightly off-center:

<br>

https://user-images.githubusercontent.com/101254295/162458000-05daefcd-e1a4-43cf-8675-79ebf52307bd.mov

<hr>

Instead of creating a new issue, I would also like to propose to automaticly select/highlight the text when the menu bar text is pressed, so you can edit the text without selecting it; make `Enter` key work as `Save` and exit the edit window when `Save` or `Enter` is pressed.

**Comment by bennyscripts** [comment]
The padding/height issue with the window will be fixed in v1.0.5.
Im pretty sure the about button does work but doesnt bring the window to the front so you will need to click the Menu Note app to see the window.
And the edit note popover will have to be closed and opened again to be re centered. I dont know anyway to prevent this.

Your proposed features seem great and i will implement them in v1.0.5.

And a little sneak peak of v1.0.5 whilst im here too
<img width="437" alt="image" src="https://user-images.githubusercontent.com/83777519/162462983-c3bf0675-d0e1-4a4b-81e7-bb899fe2d9fc.png">

**Comment by Zabriskije** [comment]
History / list: nice! And you're right on the `About` button.
Oh, also: what about make the cursor follow the text when typing? If you input a text longer than the text box you can't see what you're typing.

**Comment by bennyscripts** [comment]
The list is for multiple notes to select between different ones and following the cursor would be great, ill see if thats a possibility.
